server:
  port: 9090

ocr:
  tessdataPath: ${TESSDATA_PREFIX:${user.dir}/tessdata}
  lang: eng+ara
  whitelist: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZابجدھوزحطيكلمنسعفصقرشتثخذضظغدبيأبوظبيالشارقةعجمانرأسالخيمةالفجيرةامالقيوين"

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

