server:
  port: 9090

ocr:
  tessdataPath: ${TESSDATA_PREFIX:${user.dir}/tessdata}
  lang: eng+ara

  whitelist: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ دبي ابوظبي الشارقة عجمان رأس الخيمةالفجيرة ام القيوين"
